# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @rdname fastdm
#' @export
dfastdm <- function(rt_r, parameters_r, is_lower = TRUE) {
    .Call('_ddModel_dfastdm', PACKAGE = 'ddModel', rt_r, parameters_r, is_lower)
}

#' @rdname fastdm
#' @export
pfastdm <- function(rt_r, parameters_r, is_lower = TRUE) {
    .Call('_ddModel_pfastdm', PACKAGE = 'ddModel', rt_r, parameters_r, is_lower)
}

#' @rdname fastdm
#' @export
rfastdm <- function(n = 1L, parameters_r = as.numeric( c()), time_parameters_r = as.numeric( c()), debug = FALSE) {
    .Call('_ddModel_rfastdm', PACKAGE = 'ddModel', n, parameters_r, time_parameters_r, debug)
}

#' @rdname simulate_ddm_trials
#' @export
validate_ddm_parameters <- function(rt_model_r, parameters_r, debug = FALSE) {
    .Call('_ddModel_validate_ddm_parameters', PACKAGE = 'ddModel', rt_model_r, parameters_r, debug)
}

#' @rdname simulate_ddm_trials
#' @export
simulate_ddm_trials <- function(rt_model_r, parameters_r, time_parameters_r = as.numeric( c()), n_trial = 1L, debug = FALSE) {
    .Call('_ddModel_simulate_ddm_trials', PACKAGE = 'ddModel', rt_model_r, parameters_r, time_parameters_r, n_trial, debug)
}

